service: fightdb-game

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  environment:
    MONGODB_URL: ${self:custom.secrets.MONGODB_URL}

functions:
  createGame:
    handler: handler.createGame
    events:
      - http:
          path: game
          method: post
          cors: true

  updateGame:
    handler: handler.updateGame
    events:
      - http:
          path: game/{id}
          method: put
          cors: true

  deleteGame:
    handler: handler.deleteGame
    events:
      - http:
          path: game/{id}
          method: delete
          cors: true

  game:
    handler: handler.game
    events:
      - http:
          path: game/{id}
          method: get
          cors: true

  games:
    handler: handler.game
    events:
      - http:
          path: game
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-secrets-plugin

custom:
  serverless-offline:
    region: "ap-southeast-1"
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}
