service: fightdb-users-profile-api

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"

functions:
  create:
    handler: create.main
    events:
      - http:
          path: users
          method: post
          cors: true
  get:
    handler: get.main
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-1:820406451902:userpool/ap-northeast-1_KTLhVsKZi
  update:
    handler: update.main
    events:
      - http:
          path: users/{id}
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-1:820406451902:userpool/ap-northeast-1_KTLhVsKZi
  delete:
    handler: delete.main
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:ap-northeast-1:820406451902:userpool/ap-northeast-1_KTLhVsKZi
