service: fightdb-user

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  environment:
    MONGODB_URL: ${self:custom.secrets.MONGODB_URL}

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  updateUserInfo:
    handler: handler.updateUserInfo
    events:
      - http:
          path: user/info/{id}
          method: put
          cors: true

  updateUserSocial:
    handler: handler.updateUserSocial
    events:
      - http:
          path: user/social/{id}
          method: put
          cors: true

  updateUserGroups:
    handler: handler.updateUserGroups
    events:
      - http:
          path: user/groups/{id}
          method: put
          cors: true

  updateUserGames:
    handler: handler.updateUserGames
    events:
      - http:
          path: user/games/{id}
          method: put
          cors: true

  updateUserPassword:
    handler: handler.updateUserPassword
    events:
      - http:
          path: user/password/{id}
          method: put
          cors: true

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  user:
    handler: handler.user
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-secrets-plugin

custom:
  serverless-offline:
    region: "ap-southeast-1"
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}
